name: kovalskia
description: "Create By Elsan"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  intl: ^0.20.2
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  crypto: ^3.0.6
  email_otp: ^3.0.2
  pinput: ^5.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  photo_view: ^0.15.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/elaelaela.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
